@hostname = {{$dotenv HOSTNAME}}
@port = {{$dotenv PORT}}
@host = {{hostname}}:{{port}}
@contentType = application/json

# @name inspectGmail
POST http://{{host}}/api/v1/imx HTTP/1.1
Content-Type: {{contentType}}

{
    "email": "fc@hyperd.sh"
}

###

# @name inspectProton
POST http://{{host}}/api/v1/imx HTTP/1.1
Content-Type: {{contentType}}

{
    "email": "f@pm.me"
}

###

# @name inspectAndValidateExtras
POST http://{{host}}/api/v1/imx HTTP/1.1
Content-Type: {{contentType}}

{
    "email": "f@yahoo.co.uk"
}

###

# @name inspectAndReject
POST http://{{host}}/api/v1/imx HTTP/1.1
Content-Type: {{contentType}}

{
    "email": "f@yandex.ru"
}